stages:
   - Building & migration

build:
  stage: Building & migration
  commands:
     - ls

pre-build:
  script:
    - ls

post-build:
  script:
    - ls -la

projects:
    - name: Laravel
      platform: alpine:latest
      commands:
        - apk add php7 php7-bcmath php7-bz2 php7-common php7-ctype php7-dba php7-fileinfo php7-gd php7-json php7-mbstring php7-mysqlnd php7-openssl php7-pdo php7-pdo_mysql php7-simplexml php7-tokenizer php7-xml php7-zip php7-phar php7-dom php7-session curl
        - php --ini
        - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
        - CHECKOUT
        - composer install
      expose: 8080
      to-start:
        - php artisan migrate && php artisan serve --host=0.0.0.0 --port=8080
      service:
        - name: laravel-demo
          port: 8080
      host:
        - name: laravel-demo.devops5d.com
